/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Pdf */
        post: operations["extract_pdf_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Block */
        Block: {
            type: components["schemas"]["BlockType"];
            /** Content */
            content: string;
            /** Page */
            page: number;
            /** Confidence */
            confidence: number;
        };
        /**
         * BlockType
         * @enum {string}
         */
        BlockType: "heading" | "text" | "table";
        /** Body_extract_pdf_extract_post */
        Body_extract_pdf_extract_post: {
            /**
             * Pdf File
             * Format: binary
             */
            pdf_file: string;
        };
        /** ExtractionResponse */
        ExtractionResponse: {
            /** Book Id */
            book_id: string;
            status: components["schemas"]["ExtractionStatus"];
            /** Overall Confidence */
            overall_confidence: number;
            /** Page Count */
            page_count: number;
            /** Blocks */
            blocks: components["schemas"]["Block"][];
        };
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "success" | "partial" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_pdf_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_pdf_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
